workspace:
  base: /go
  path: src/github.com/go-training/drone-golang-example

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  testing:
    image: golang:1.10.0
    commands:
      - go test -v .
      - go vet

  build_linux_amd64:
    image: golang:1.10.0
    group: build
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -v -a -o release/linux/amd64/helloworld

  build_linux_i386:
    image: golang:1.10.0
    group: build
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=386
    commands:
      - go build -v -a -o release/linux/i386/helloworld
