kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: testing
  image: golang:1.11
  pull: true
  commands:
  - go test -v .
  - go vet

- name: build_linux_amd64
  image: golang:1.11
  group: build
  pull: true
  commands:
  - make build_linux_amd64

- name: build_linux_i386
  image: golang:1.11
  group: build
  pull: true
  commands:
  - make build_linux_i386

#   publish_linux_amd64:
#     image: plugins/docker:17.05
#     pull: true
#     secrets: [ docker_username, docker_password ]
#     group: release
#     repo: appleboy/test
#     auto_tag: true
#     dockerfile: Dockerfile
#     when:
#       event: [ push, tag ]
#       local: false

#   publish_alpine:
#     image: plugins/docker
#     group: release
#     pull: true
#     dockerfile: Dockerfile.alpine
#     secrets: [ docker_username, docker_password ]
#     default_tags: true
#     default_suffix: alpine
#     repo: appleboy/test
#     when:
#       event: [ push, tag ]
#       local: false
