kind: pipeline
type: docker
name: linux_amd64

steps:
- name: build-linux-amd64
  image: golang:1.17
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  commands:
  - make build

---
kind: pipeline
type: docker
name: linux_386

steps:
- name: build-linux-386
  image: golang:1.17
  environment:
    GOOS: linux
    GOARCH: 386
    CGO_ENABLED: 0
  commands:
  - make build
