workspace:
  base: /go
  path: src/github.com/go-training/drone-golang-example

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: golang:1.9
    pull: true
    commands:
      - go vet
      - |
        for PKG in $(go list ./... | grep -v /vendor/); do
          go test -cover -coverprofile $PKG/coverage.out $PKG
        done

  backend:
    image: golang:1.9.2
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -v -a -o release/linux/amd64/helloworld
