kind: pipeline
name: default

steps:
- name: build
  image: golang:1.13
  commands:
  - make build_linux_amd64

- name: event promote
  image: golang:1.13
  commands:
  - echo "event promote"
  when:
    event:
    - promote
    
- name: event rollback
  image: golang:1.13
  commands:
  - echo "event rollback"
  when:
    event:
    - rollback
    
- name: target staging
  image: golang:1.13
  commands:
  - echo "staging"
  when:
    target:
    - staging
    
- name: target production
  image: golang:1.13
  commands:
  - echo "production"
  when:
    target:
    - production

- name: drone server 1
  image: golang:1.13
  commands:
  - echo "9f47284e"
  when:
    instance:
    - 9f47284e.ngrok.io
    
- name: drone server 2
  image: golang:1.13
  commands:
  - echo "9f472842"
  when:
    instance:
    - 9f472842.ngrok.io

- name: docker
  image: plugins/docker
  settings:
    registry: docker.pkg.github.com
    repo: docker.pkg.github.com/appleboy/test/helloworld
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username: appleboy
    password:
      from_secret: docker_password
  when:
    target:
    - production
