kind: pipeline
type: docker
name: node1

steps:
- name: build
  image: golang:1.13
  commands:
  - make build_linux_amd64

---
kind: pipeline
type: docker
name: node2

steps:
- name: build
  image: golang:1.13
  commands:
  - make build_linux_amd64
