workspace:
  base: /go
  path: src/drone-golang-example

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: golang
    commands:
      - echo "backend testing"

  frontend:
    image: golang
    commands:
      - echo "frontend testing"

  deploy:
    image: golang
    commands:
      - echo "deploy"
    when:
      local: false
