kind: pipeline
name: testing

clone:
  depth: 50

steps:
- name: testing
  image: golang:1.11
  pull: true
  commands:
  - go test -v .
  - go vet

---
kind: pipeline
name: build_linux_i386

clone:
  depth: 50

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: binary
  image: golang:1.11
  pull: true
  commands:
  - make build_linux_i386

---
kind: pipeline
name: build_linux_amd64

clone:
  depth: 50

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: binary
  image: golang:1.11
  pull: true
  commands:
  - make build_linux_amd64

- name: publish
  image: plugins/docker:17.12
  settings:
    repo: appleboy/test
    auto_tag: true
    dockerfile: Dockerfile
    docker_username:
      from_secret: docker_username
    docker_password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

#   publish_linux_amd64:
#     image: plugins/docker:17.05
#     pull: true
#     secrets: [ docker_username, docker_password ]
#     group: release
#     repo: appleboy/test
#     auto_tag: true
#     dockerfile: Dockerfile
#     when:
#       event: [ push, tag ]
#       local: false

#   publish_alpine:
#     image: plugins/docker
#     group: release
#     pull: true
#     dockerfile: Dockerfile.alpine
#     secrets: [ docker_username, docker_password ]
#     default_tags: true
#     default_suffix: alpine
#     repo: appleboy/test
#     when:
#       event: [ push, tag ]
#       local: false
